services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: agente-agenda:dev

  nginx:
    ports:
      - "8080:80"

  redis:
    ports:
      - "6379:6379"

networks:
  web:
    external: false
    name: agente-agenda_web
