"""initial_revision

Revision ID: b0021778e045
Revises: 
Create Date: 2026-05-16 14:00:30.810315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0021778e045'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=18), nullable=False),
    sa.Column('document_type', sa.Enum('CPF', 'CNPJ', name='documenttype'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('neighborhood', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_global_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establishment_id', 'phone', name='uq_clients_establishment_phone')
    )
    op.create_index('idx_clients_establishment_active', 'clients', ['establishment_id', 'is_active'], unique=False)
    op.create_index('idx_clients_establishment_phone', 'clients', ['establishment_id', 'phone'], unique=False)
    op.create_index('uq_clients_establishment_email', 'clients', ['establishment_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('messaging_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('CONFIRMATION', 'REMINDER', 'CANCELLATION', name='templatetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('minutes_before', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messaging_templates_establishment_active', 'messaging_templates', ['establishment_id', 'is_active'], unique=False)
    op.create_table('operating_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_operating_hours_time_range'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_operating_hours_weekday_range'),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operating_hours_establishment', 'operating_hours', ['establishment_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_services_duration_minutes_positive'),
    sa.CheckConstraint('price >= 0', name='ck_services_price_non_negative'),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establishment_id', 'name', name='uq_services_establishment_name')
    )
    op.create_index('idx_services_establishment_active', 'services', ['establishment_id', 'is_active'], unique=False)
    op.create_index('idx_services_establishment_name', 'services', ['establishment_id', 'name'], unique=False)
    op.create_table('user_establishments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ESTABLISHMENT_ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'establishment_id', name='uq_user_establishment')
    )
    op.create_table('schedulings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='schedulingstatus'), nullable=False),
    sa.Column('source', sa.Enum('WHATSAPP', 'APP', name='schedulingsource'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_by_type', sa.Enum('CLIENT', 'ESTABLISHMENT', 'SYSTEM', name='cancelledbytype'), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedulings_client_id', 'schedulings', ['client_id'], unique=False)
    op.create_index('idx_schedulings_establishment', 'schedulings', ['establishment_id'], unique=False)
    op.create_index('idx_schedulings_starts_at', 'schedulings', ['starts_at'], unique=False)
    op.create_index('idx_schedulings_status', 'schedulings', ['status'], unique=False)
    op.create_index('idx_schedulings_user_id', 'schedulings', ['user_id'], unique=False)
    op.create_table('service_messaging_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_type', sa.Enum('CONFIRMATION', 'REMINDER', 'CANCELLATION', name='templatetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['messaging_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'template_type', name='uq_service_messaging_template_type')
    )
    op.create_index('idx_service_messaging_template_service_id', 'service_messaging_templates', ['service_id'], unique=False)
    op.create_index('idx_service_messaging_template_template_id', 'service_messaging_templates', ['template_id'], unique=False)
    op.create_table('scheduling_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('scheduling_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'cancelled', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('content_at_send', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduling_id'], ['schedulings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['messaging_templates.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduling_notifications_establishment', 'scheduling_notifications', ['establishment_id'], unique=False)
    op.create_index('idx_scheduling_notifications_scheduled_at', 'scheduling_notifications', ['scheduled_at'], unique=False)
    op.create_index('idx_scheduling_notifications_scheduling', 'scheduling_notifications', ['scheduling_id'], unique=False)
    op.create_index('idx_scheduling_notifications_status', 'scheduling_notifications', ['status'], unique=False)
    op.create_table('scheduling_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduling_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='schedulingstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='schedulingstatus'), nullable=False),
    sa.Column('changed_by_source', sa.Enum('USER', 'CLIENT', 'SYSTEM', name='changedbysource'), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduling_id'], ['schedulings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduling_status_logs_scheduling_id', 'scheduling_status_logs', ['scheduling_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scheduling_status_logs_scheduling_id', table_name='scheduling_status_logs')
    op.drop_table('scheduling_status_logs')
    op.drop_index('idx_scheduling_notifications_status', table_name='scheduling_notifications')
    op.drop_index('idx_scheduling_notifications_scheduling', table_name='scheduling_notifications')
    op.drop_index('idx_scheduling_notifications_scheduled_at', table_name='scheduling_notifications')
    op.drop_index('idx_scheduling_notifications_establishment', table_name='scheduling_notifications')
    op.drop_table('scheduling_notifications')
    op.drop_index('idx_service_messaging_template_template_id', table_name='service_messaging_templates')
    op.drop_index('idx_service_messaging_template_service_id', table_name='service_messaging_templates')
    op.drop_table('service_messaging_templates')
    op.drop_index('idx_schedulings_user_id', table_name='schedulings')
    op.drop_index('idx_schedulings_status', table_name='schedulings')
    op.drop_index('idx_schedulings_starts_at', table_name='schedulings')
    op.drop_index('idx_schedulings_establishment', table_name='schedulings')
    op.drop_index('idx_schedulings_client_id', table_name='schedulings')
    op.drop_table('schedulings')
    op.drop_table('user_establishments')
    op.drop_index('idx_services_establishment_name', table_name='services')
    op.drop_index('idx_services_establishment_active', table_name='services')
    op.drop_table('services')
    op.drop_index('idx_operating_hours_establishment', table_name='operating_hours')
    op.drop_table('operating_hours')
    op.drop_index('idx_messaging_templates_establishment_active', table_name='messaging_templates')
    op.drop_table('messaging_templates')
    op.drop_index('uq_clients_establishment_email', table_name='clients', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('idx_clients_establishment_phone', table_name='clients')
    op.drop_index('idx_clients_establishment_active', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('establishments')
    # ### end Alembic commands ###
